### ISSUE TITLE
Absorb ecstatic like the borg

### ISSUE THREAD

**Issue by thornjad** [thornjad/http-server-1#1]
- [x] Move the whole ecstatic library into this repo
- [ ] replace all usage of ecstatic with the internal library
- [ ] check out extatic fork for improvements
- [ ] expose/implement all features of ecstatic which we want in http-server functionality
- [ ] remove any parts of ecstatic which are unused
- [ ] fully internalize local ecstatic library as modules in `lib/` dir
- [ ] tests, tests, tests, tests
- [ ] drop all internal reference to `ecstatic`
- [ ] ensure readme talks about and thanks the ecstatic project for all the work which is now contained within http-server
