### ISSUE TITLE
Implement full-featured and extensible API

### ISSUE THREAD

**Issue by thornjad** [thornjad/http-server-1#2]
- [ ] Define a common API call format
- [ ] Document format
- [ ] Ensure all CLI options are easily available as API calls to the lib, adhering to established call format
- [ ] At least two tests for every function and option. There should be so many tests it looks ridiculous.
- [ ] Restructure CLI script in `bin/` to be a TTY interface to the lib only
- [ ] Allow extensibility wherever possible
  - [ ] accept functions into options which return the desired option
  - [ ] allow insertion of middleware
- [ ] Document API
  - [ ] Decide location, should it be in the GH wiki? GH pages? All Markdown?
  - [ ] Man page for CLI options, with reference to the full API documentation
