### ISSUE TITLE
Internalize and replace union dependency

### ISSUE THREAD

**Issue by thornjad** [thornjad/http-server-1#4]
- [ ] Move entire union library into internal `lib/` directory
- [ ] Replace all usage of union with internal library
- [ ] Investigate total replacement of union with modern native Node utilities, or another, smaller project
  - [ ] Create plan
  - [ ] Execute
